### PR TITLE
Feat/Add sensor_name to the tagged json

### PR DESCRIPTION
**Pull request by vikgmdev**
## Contributor Comments

- Add `sensor_name` parameter
- Refactor the TaggedJson to get a better-formatted output:
```
{
    "sensor_name": "sensor_Vagrant1", 
    "event_type": "bro_dns", 
    "data": { 
         <LOG>
    }
}
```

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron's Bro kafka writer plugin.

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [ ] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed via:
  ```
  bro-pkg test $GITHUB_USERNAME/metron-bro-plugin-kafka --version $BRANCH
  ```
- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Apache Metron's [Vagrant full-dev environment](https://github.com/apache/metron/tree/master/metron-deployment/development/centos6) or the equivalent?

### CODE REVIEW

**Comment by vikgmdev** [comment]
This PR was intended to be created on my own fork as a custom feat that I need.

**Comment by ottobackwards** [comment]
What might be more generic would be to define a table or something that would have names and values to add to each message, so it wasn't tied to "sensor"

**Comment by vikgmdev** [comment]
> What might be more generic would be to define a table or something that would have names and values to add to each message, so it wasn't tied to "sensor"

I didn't think about that but sounds very suitable for what I need. I'm going to read the Contribution Guidelines. Thanks!

**Comment by JonZeolla** [comment]
Hi, checking in to see how things are coming along and if you were interested in contributing to the package 😁

**Comment by vikgmdev** [comment]
Hi @JonZeolla, to be honest, I don't know too much about C++ but It's a good opportunity to learn, so take me into account for contributions, do you have a backlog or from where I can start?

**Comment by ottobackwards** [comment]
@vikgmdev https://github.com/apache/metron-bro-plugin-kafka/pull/46 has landed and will give you the functionality you are looking for I think

**Comment by vikgmdev** [comment]
Hey @ottobackwards, I saw the changed this morning, It's exactly what I was looking for thanks for that!

**Pull request closed without merging**
