### PR TITLE
METRON-1992: Support sending a log to multiple topics

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
The bro plugin is currently unable to send a single bro log to multiple different kafka topics in the same kafka cluster. In order to support the ability to do streaming enrichment of bro logs using bro logs from the same bro cluster, this should be supported.

### Testing
- [x] Confirm functional in a physical deployment
- [x] Tests in docker

More details on how to test and what to expect are @ https://github.com/apache/metron-bro-plugin-kafka/pull/23#issuecomment-463325732

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron's Bro kafka writer plugin.

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [X] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed via:
  ```
  bro-pkg test $GITHUB_USERNAME/metron-bro-plugin-kafka --version $BRANCH
  ```
- [ ] Have you written or updated unit tests and or integration tests to verify your changes?

### CODE REVIEW

**Comment by ottobackwards** [comment]
We may need a change to the docker stuff to have multiple topics

**Comment by JonZeolla** [comment]
Yup I expect that.  I'm going to put some time into seeing how that would look.  I have some ideas

**Comment by JonZeolla** [comment]
I need to make a small change to KafkaWriter::DoInit so we can override the topic_name in a one-off log filter, potentially among other things

**Comment by JonZeolla** [comment]
Docker tests are successful, going to test this on my physical cluster soon.

**Comment by JonZeolla** [comment]
This depends on METRON-1910 because otherwise it segfaults everywhere.

**Comment by JonZeolla** [comment]
By the way, I found the following helpful when validating this works via docker.
```
diff --git a/docker/in_docker_scripts/configure_bro_plugin.sh b/docker/in_docker_scripts/configure_bro_plugin.sh
index 74551c2..7eb2c2c 100755
--- a/docker/in_docker_scripts/configure_bro_plugin.sh
+++ b/docker/in_docker_scripts/configure_bro_plugin.sh
@@ -29,12 +29,22 @@ echo "Configuring kafka plugin"
 {
   echo "@load packages"
   echo "redef Kafka::logs_to_send = set(HTTP::LOG, DNS::LOG, Conn::LOG, DPD::LOG, FTP::LOG, Files::LOG, Known::CERTS_LOG, SMTP::LOG, SSL::LOG, Weird::LOG, Notice::LOG, DHCP::LOG, SSH::LOG, Software::LOG, RADIUS::LOG, X509::LOG, Known::DEVICES_LOG, RFB::LOG, Stats::LOG, CaptureLoss::LOG, SIP::LOG);"
-  echo "redef Kafka::topic_name = \"bro\";"
+  echo "redef Kafka::topic_name = \"notbro\";"
   echo "redef Kafka::tag_json = T;"
   echo "redef Kafka::kafka_conf = table([\"metadata.broker.list\"] = \"kafka:9092\");"
   echo "redef Kafka::logs_to_exclude = set(Conn::LOG, DHCP::LOG);"
   echo "redef Known::cert_tracking = ALL_HOSTS;"
   echo "redef Software::asset_tracking = ALL_HOSTS;"
+  echo 'event bro_init() &priority=-10
+{
+    # Also send RADIUS to the bro topic
+    local shew_radius_filter: Log::Filter = [
+        $name = "kafka-radius-shew",
+        $writer = Log::WRITER_KAFKAWRITER,
+       $config = table(["topic_name"] = "bro")
+    ];
+    Log::add_filter(RADIUS::LOG, shew_radius_filter);
+}'
 } >> /usr/local/bro/share/bro/site/local.bro

 sed -i '86 a @load policy/protocols/dhcp/known-devices-and-hostnames.bro' /usr/local/bro/share/bro/site/local.bro
```

**Comment by JonZeolla** [comment]
I'm running this in my prod environment, no issues.  Also replicated the fix in docker, all good.

**Comment by JonZeolla** [comment]
Whups, it looks like I had butchered README earlier.  That most recent commit should fix it and the example now shows sending 3 logs to the bro topic, and sending 2 of those 3 logs to additional unique topics.

**Comment by JonZeolla** [comment]
FYI @nickwallen, since we briefly discussed this issue.

**Comment by JonZeolla** [comment]
Ok this should be good to go, merged master and deconflicted.

**Comment by ottobackwards** [comment]
@JonZeolla, when I run the docker set with your modifications, what should I see if this works correctly please?

**Comment by JonZeolla** [comment]
0. Clone this PR locally and cd into the root dir.
1. Apply https://github.com/apache/metron-bro-plugin-kafka/pull/23#issuecomment-461897366
1. `cd docker/`
1. `./run_end_to_end.sh [--skip-docker-build]`
1. `echo $?`
1. `cd test_output/$(ls -t test_output | head -1)`
1. `cat */kafka-output.log`
1. Expect the following:
```
{"shew_bro_radius": {"ts":1440447766.440305,"uid":"C2ISs82zVTu2ycQBki","id.orig_h":"127.0.0.1","id.orig_p":53031,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","framed_addr":"172.16.3.33","result":"failed","ttl":1.005906}}
{"shew_bro_radius": {"ts":1440447839.947454,"uid":"CbCLLB2dCvuE12Y4zf","id.orig_h":"127.0.0.1","id.orig_p":65443,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","framed_addr":"172.16.3.33","result":"success","ttl":0.000779}}
{"shew_bro_radius": {"ts":1440447848.196115,"uid":"CKuRzs2QX7zaGxlQca","id.orig_h":"127.0.0.1","id.orig_p":57717,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","result":"success","ttl":0.000275}}
{"shew_bro_radius": {"ts":1440447860.613743,"uid":"Ctv6Rj29b9zQ2uKUb7","id.orig_h":"127.0.0.1","id.orig_p":64691,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","result":"success","ttl":0.000273}}
{"shew_bro_radius": {"ts":1440447880.931272,"uid":"CGeCdz385lCcncIMP4","id.orig_h":"127.0.0.1","id.orig_p":52178,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","result":"failed","ttl":1.001459}}
{"shew_bro_radius": {"ts":1440447904.122012,"uid":"CLyJlXr5xUcAuD53c","id.orig_h":"127.0.0.1","id.orig_p":62956,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","result":"unknown"}}
{"shew_bro_radius": {"ts":1440448190.335333,"uid":"Clf2c41J17gmRMfzc8","id.orig_h":"127.0.0.1","id.orig_p":53127,"id.resp_h":"127.0.0.1","id.resp_p":1812,"username":"steve","result":"success","ttl":0.000517}}
```
Notably:  There should only be 7 radius logs, all tagged with "shew_bro_radius".  This demonstrates that only the radius logs that were expected were properly sent to the overridden kafka topic name of "bro".

**Comment by ottobackwards** [comment]
+1

**Pull request closed without merging**
