### PR TITLE
METRON-1768: Adjust versioning of metron-bro-plugin-kafka to be x.y.z

### PR DESCRIPTION
**Pull request by JonZeolla**

### CODE REVIEW

**Comment by ottobackwards** [comment]
+1

**Comment by mmiklavc** [comment]
+1 via inspection

**Comment by JonZeolla** [comment]
This is on hold, pending bro/bro#152

**Comment by JonZeolla** [comment]
My PRs to the bro stack were merged, but it won't be available until bro 2.7 is released.  Currently they are beta testing 2.6.

**Comment by JonZeolla** [comment]
This is no longer waiting on a 3.0 release.  Depends on #44

**Pull request closed without merging**
