### PR TITLE
METRON-1407: Metron-Bro-Kafka plugin unable to find correct libkafka library.

### PR DESCRIPTION
**Pull request by z0r0**
find_library was failing. I found this typo, and it solved my issue.

### CODE REVIEW

**Comment by JonZeolla** [comment]
Great catch, thanks @z0r0 I will check this out soon.  Not sure why this isn't auto linking to https://issues.apache.org/jira/browse/METRON-1407 though...

I can't assign this JIRA to you yet, I need to get you added as a contributor.  I've reached out to @ottobackwards via IRC to see if he can help, otherwise someone can shoot an email to the dev@ mailing list for you to be added.

**Comment by ottobackwards** [comment]
I believe the linking *is* working.  Maybe it is just lagged.
As far as Jira rights, I'm looking into it, but I cannot as of this moment execute that

**Comment by JonZeolla** [comment]
There we go, yeah that was significantly more delayed than normal.  

@z0r0 Would you mind sending an email to the dev list to get you added as a contributor on Jira so we can assign this to you?  Thanks

**Comment by JonZeolla** [comment]
+1

**Pull request closed without merging**
