### PR TITLE
METRON-2045: Pass a version argument to the bro plugin docker scripts

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
`bro-pkg` recently released version 1.5.4, and now we can specify commit hashes as versions (in addition to branches and tags). This could be helpful when troubleshooting the plugin at specific points in time, and came up as a part of [METRON-2044](https://issues.apache.org/jira/browse/METRON-2044).

### Testing
You will need to rebuild your bro container in order to get the latest version of `bro-pkg`.

**Test 1**
Make sure it still installs the currently checked out branch by default.
```
$ git checkout METRON-2045
$ cd docker/
$ ./run_end_to_end.sh --skip-docker-build
$ ./scripts/docker_execute_shell.sh
# cd code/
# git status
# On branch METRON-2045
nothing to commit, working directory clean
# bro-pkg list
/root/code (installed: METRON-2045) - A Bro log writer plugin that sends logging output to Kafka.
```

**Test 2**
Make sure it will install a provided commit hash, when provided.
```
$ git checkout METRON-2045
$ cd docker/
$ ./run_end_to_end.sh --skip-docker-build --plugin-version=b360b85e00a8d6b8db9c790c44a767a54c81eb2b
$ ./scripts/docker_execute_shell.sh
# cd code/
# git status # Expect METRON-2045 is checked out
# On branch METRON-2045
nothing to commit, working directory clean
# bro-pkg list # bro-pkg should actually install the provided commit hash
/root/code (installed: b360b85e00a8d6b8db9c790c44a767a54c81eb2b) - A Bro log writer plugin that sends logging output to Kafka.
```

Don’t forget to `./finish_end_to_end.sh` in between your testing.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron's Bro kafka writer plugin.

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [X] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [X] Have you ensured that the full suite of tests and checks have been executed via:
  ```
  ./run_end_to_end.sh
  ```
- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Apache Metron's [Vagrant full-dev environment](https://github.com/apache/metron/tree/master/metron-deployment/development/centos6) or the equivalent?

### CODE REVIEW

**Comment by JonZeolla** [comment]
1. You can specify a tag, a branch, or a commit, but you cannot specify both a branch and a commit. Are you suggesting this somewhere points to the [install command documentation](https://docs.zeek.org/projects/package-manager/en/stable/bro-pkg.html#install-command) for details on `--version`?
1. There is no change to what we currently do with `bro-pkg install code`.

I did notice that I missed adding this to the bottom of `docker/README.md` so I will do that now.

**Comment by ottobackwards** [comment]
No, I mean if I run this locally, with a commit that has not landed on master yet, what will happen?  Or is not in the branch I currently have checked out?   Or not even in my repo?
Is there some implied  " you must have the commit in the current checked out branch......" stuff that needs to be spelled out?

**Comment by JonZeolla** [comment]
I just updated `docker/README.md` with a note, is that what you were looking for?

**Comment by ottobackwards** [comment]
did you push?

**Comment by JonZeolla** [comment]
I did but it looks like this PR is actually from apache/metron-bro-plugin-kafka's METRON-2045 branch, not mine, so I need to reopen the PR and delete that.

**Pull request closed without merging**
