### PR TITLE
METRON-1303:  Reorganize the metron-bro-plugin-kafka

### PR DESCRIPTION
**Pull request by JonZeolla**
This should rename Bro to Apache everywhere that's necessary for this plugin, and fix a broken link in the README.

### CODE REVIEW

**Comment by ottobackwards** [comment]
+1 by inspection
Is there any CI build for this?  Can we get it into travis?

**Comment by ottobackwards** [comment]
or if it is building can we link that to github?

**Comment by JonZeolla** [comment]
I'm willing to bet we could get this tested using travis.  There is a built-in btest which will be automatically run on install when this is turned into a package (although it is *very* rudamentary), and I'm planning to expand the btest to include a memtest, but it is missing a lot of tests at this point and that probably needs to be a future focus.  I threw together [METRON-1305](https://issues.apache.org/jira/browse/METRON-1305) to track.

**Comment by JonZeolla** [comment]
Holding off on committing this until I hear back on my [suggested roadmap outline](https://lists.apache.org/thread.html/1e93ec4f8f126610ba359c44982bc512a338728ccdf21cebdc53d117@%3Cdev.metron.apache.org%3E).

**Pull request closed without merging**
